api:
  version: v1.0
server:
  port: 8080
  servlet:
    context-path: /price-service-rest-api/
  error:
    include-exception: true
    include-stacktrace: always
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
  api-docs:
    enabled: true
    path: /api-docs
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: demo-service
